Support for Ring door bell motion and button press
python-wink/python-wink pull request #67
Opened 2017-01-10 15:09 UTC by w1ll1am23

@scadaguru requested support for the Ring door bell sensors. This adds support.

@scadaguru If you can test, please try running the below script with your token and make sure you get the expected results. Not sure how long the states will stay active so you may need to run this while standing at your door. This won't be an issue once included in Home-Assistant because pubnub will be pushing the state changes.

```python
import pywink

pywink.set_bearer_token('YOUR TOKEN HERE')

door_bell_sensors = pywink.get_door_bells()
motion_sensor = door_bell_sensors[0]
door_bell_button = door_bell_sensors[1]
print("Motion: " + str(motion_sensor.motion_boolean()))
print("Button pressed: " + str(door_bell_button.button_pressed_boolean()))
```

2017-01-10 15:20 UTC, scadaguru commented
Nice, that was quick. I will test (couple different times: motion as well ring button pressed) the script you provided tonight and post results here. 
Thanks a lot.

2017-01-11 03:43 UTC, bradsk88 requested changes

2017-01-11 03:43 UTC, bradsk88 commented on src/pywink/api.py
> +    subsensors.append(WinkDoorBellMotion(item, api_interface))
Please add checks for the capability like in `__get_subsensors_from_sensor_pod`
This will blow up if the door bell doesn't have a motion sensor.

2017-01-11 13:07 UTC, w1ll1am23 commented on src/pywink/api.py
> +    subsensors.append(WinkDoorBellMotion(item, api_interface))
Good point. Fixed.

2017-01-11 13:12 UTC, w1ll1am23 commented
@bradsk88 I have a question. This is unrelated to this PR, but if it is an issue I would like to include it here.

in src/pywink/devices/factory.py, the very last line reads

```
return new_object or WinkDevice(device_state_as_json, api_interface)
```

What is the purpose of the `or`? What happens when a user has devices we don't support in their account? I would assume they would get to this point and get created as a base WinkDevice? However that device doesn't do anything and I would think, would/could cause issues. Can we not just return None here?

2017-01-11 16:57 UTC, scadaguru commented
I am struggling to test above sample test code, it keeps giving me:
ImportError: cannot import name 'WinkDoorBellButton'

I tried manually installing updated version but I couldn't classWinkDoorBellButton from sensor.py
I am missing something and not able find it.
Any help please?

2017-01-11 17:03 UTC, w1ll1am23 commented
@scadaguru do a git clone on this https://github.com/w1ll1am23/python-wink.git

Then cd into the new python-wink folder
then git checkout ring_doorbell
then run the above script from python-wink/src/test.py

See if that helps.

2017-01-11 19:06 UTC, scadaguru commented
Made some progress but now I am getting: 
AttributeError: module 'pywink' has no attribute 'get_door_bells'

I see api.py has method/function/attribute on line 193:
```
def get_door_bells():
    return get_devices(device_types.DOOR_BELL)

```
By the way I am using Windows 10 machine for this testing and could be cached version of python, I tried after deleting C:\Users\xxxx\AppData\Local\pip\cache still no luck.

This is what I am trying to run and I am getting back my garage door details but fails for door bell:

```
import pywink
import site; 

print(site.getsitepackages())
pywink.set_bearer_token('xxxxxxxxxxxxxxxxxxxxxxxxxxx')

my_garage = pywink.get_garage_doors()
print(my_garage)

door_bell_sensors = pywink.get_door_bells()
motion_sensor = door_bell_sensors[0]
door_bell_button = door_bell_sensors[1]
print("Motion: " + str(motion_sensor.motion_boolean()))
print("Button pressed: " + str(door_bell_button.button_pressed_boolean()))
```

2017-01-11 19:38 UTC, w1ll1am23 commented
not sure how it works in windows. can you run a pip uninstall python-wink
and then try again? make sure you are running from inside the src
directory.

On Jan 11, 2017 2:06 PM, "scadaguru" <notifications@github.com> wrote:

> Made some progress but now I am getting:
> AttributeError: module 'pywink' has no attribute 'get_door_bells'
>
> I see api.py has method/function/attribute on line 193:
>
> def get_door_bells():
>     return get_devices(device_types.DOOR_BELL)
>
>
> By the way I am using Windows 10 machine for this testing and could be
> cached version of python, I tried after deleting
> C:\Users\xxxx\AppData\Local\pip\cache still no luck.
>
> This is what I am trying to run and I am getting back my garage door
> details but fails for door bell:
>
> import pywink
> import site;
>
> print(site.getsitepackages())
> pywink.set_bearer_token('xxxxxxxxxxxxxxxxxxxxxxxxxxx')
>
> my_garage = pywink.get_garage_doors()
> print(my_garage)
>
> door_bell_sensors = pywink.get_door_bells()
> motion_sensor = door_bell_sensors[0]
> door_bell_button = door_bell_sensors[1]
> print("Motion: " + str(motion_sensor.motion_boolean()))
> print("Button pressed: " + str(door_bell_button.button_pressed_boolean()))
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python-wink/python-wink/pull/67#issuecomment-271963421>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGIoAv6G6LOEgh9GLmphj-K0yf-5g0ngks5rRSg8gaJpZM4LfhH6>
> .
>

2017-01-11 19:48 UTC, scadaguru commented
I have done that uninstall/reinstall but no help.
I just noticed something in github of ring_doorbell that __init__.py never got changed and has no mention of get_door_bells, is that something needs to be updated?

2017-01-11 19:51 UTC, w1ll1am23 commented
Good call, i always forget that. That's most likely the issue. You can
manually add it, I will fix it in a few minutes.

On Jan 11, 2017 2:48 PM, "scadaguru" <notifications@github.com> wrote:

> I have done that uninstall/reinstall but no help.
> I just noticed something in github of ring_doorbell that *init*.py never
> got changed and has no mention of get_door_bells, is that something needs
> to be updated?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python-wink/python-wink/pull/67#issuecomment-271974437>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGIoAsl8Anq62CjM1oF5gN8nMfnKY4AZks5rRTILgaJpZM4LfhH6>
> .
>

2017-01-11 21:01 UTC, scadaguru commented
Yay,
It worked. I have successfully tested motion and ring events and both of them reported correctly "true" using above mentioned test script. 
Thanks for your work, hopefully this gets included into Home Assistant soon. Not sure what else to change in HA to get those two sensor before HA next release may be just wink.py from components folder?
Thanks once again.

2017-01-11 21:14 UTC, w1ll1am23 commented
@scadaguru Sweet, thanks for testing. Yeah, once this gets merged in I will start on the home-assistant changes, going to need a new wink.py and a binary_sensors/wink.py. I will mention you on the home-assistant pull request and indicate how to test.

2017-01-12 05:16 UTC, bradsk88 approved these changes

2017-01-12 05:16 UTC, merged

2017-01-12 05:17 UTC, bradsk88 commented
@w1ll1am23 Published 0.13.0 :dolls: